=== Hoetech/Web-Refactoring/categories.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://localhost/rssfeed"
    xmlns="http://localhost/rssfeed"
    elementFormDefault="qualified">

  <xs:element name="categories">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="category" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="category_id" type="xs:integer" />
              <xs:element name="name" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Hoetech/Web-Refactoring/categories.xml
<categories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://localhost/rssfeed categories.xsd" xmlns="http://localhost/rssfeed">
  <category>
    <category_id>1</category_id>
    <name>Entertainment</name>
  </category>
  <category>
    <category_id>2</category_id>
    <name>Sports</name>
  </category>
  <category>
    <category_id>4</category_id>
    <name>History</name>
  </category>
</categories>
